# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 348d0edc9ba3cfa1158fd45fb8fbfb3a917a24724a5787fb44ef726c7c875c02a98d4df283bb9d7cdeca17699012263005d6ccce4f82360b3f50a06410ac8ce7

test:
  secret_key_base: ab2a4cbf3be6b2804cd457bca783d41afddaa4f4e96f097f09c9727a77f21ac37273dc91291a7d0a1817d8cf189d4751e8084f5c8b562481db732b970e24031b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
